name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Build Webpack
        run: npm run build:webpack

      - name: Build Typescript
        run: npm run build:tsc

      - name: Package Electron
        run: npx electron-builder --publish=never

      - name: Echo Version
        run: echo "${{ github.ref }}".Split('/')[-1].Substring(1)

      - name: Set Version
        run: echo "VERSION=$(echo "${{ github.ref }}".Split('/')[-1].Substring(1))" >> $GITHUB_ENV

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ github.event.repository.releases_url }}
          asset_path: ./bin/GoXLR Mic Light Setup ${{ env.VERSION }}.exe
          asset_name: GoXLR Mic Light Setup ${{ env.VERSION }}.exe
          asset_content_type: application/octet-stream
